# Workflow

# tittle: Website Name
# description : A website for uploading content


# #Array
# tags:
# -technology
# -images
# -creative

# #objects
# address:
# street: MG Road
# City: Bng
# State: KA

name: Github action ofr
on:
  push:
    branches: [master]
  jobs:
   build:
     runs-on: ubantu-latest
     steps:
       -uses: actions/checkout@v3
       -name: Print node version
        run: node --version
      - name: Print NPM version
        run: npm --version
      - name: Print pwd
        run: pwd 